### PR TITLE
Decision Tree from Scratch with Readme for folder

### PR DESCRIPTION
**Pull request by kparitosh21**
Worked a lot on it,
Kindly go through the pr and the readme of the same folder and let me know if any changes required :) 
Now I'm working on Recommendation Engines.

### CODE REVIEW

**Comment by Lightning-Bug** [comment]
??

**Comment by Lightning-Bug** [comment]
??????
4 days and no reply??

**Comment by aribis369** [comment]
@Lightning-Bug Sorry buddy, was busy for somedays. I checked your work. It's  really good. 
Any type of query or delay in process please mail me first, sometimes we get pass the notifications from Github which may cause such overlooks.

**Comment by aribis369** [comment]
Merged.

**Comment by kparitosh21** [comment]
@aribis369 Thank You :)) 
I respect your busy schedule, was a bit tensed as these are last days na ....
Sure, I will take care of that.
Thanks anyways :))

**Comment by aribis369** [comment]
@Lightning-Bug No problem. Feel free to approach.

**Comment by kparitosh21** [comment]
Hello,
I've created a PR.
I Know it may not be evaluated for kwoc but if you like it, you can merge :)

https://github.com/aribis369/ML-Starter-Pack/pulls?q=is%3Aopen+is%3Apr

Thank you
Paritosh

**Comment by aribis369** [comment]
Hi Paritosh,

Nice to know that you have worked on this project even after KWoC is over.
This should be the spirit of contribute of contributing to open-source.

Regards,
Arindam.

**Pull request merged**
