### PR TITLE
Added Logistic Regression

### PR DESCRIPTION
**Pull request by dhruvapte26**
A good starter PR :sweat_smile:

### CODE REVIEW

**Comment by aribis369** [comment]
@the-ethan-hunt Please add a Jupyter notebook( should be very well descriptive ) for this code.

**Comment by dhruvapte26** [comment]
Alright @aribis369  :smile:

**Comment by dhruvapte26** [comment]
@aribis369 I have added the `.ipynb`. Would you please check it. :smile:

**Comment by aribis369** [comment]
@the-ethan-hunt Nice work. Very descriptive. I would merge this PR but I may squash your 4 commits into i commit, if there's no problem.

**Comment by dhruvapte26** [comment]
Peace :smile:  @aribis369

**Comment by aribis369** [comment]
@the-ethan-hunt Merged.

**Pull request merged**
