### PR TITLE
NaiveBayes And SVM

### PR DESCRIPTION
**Pull request by Culeshovi**
A Naive Bayes and SVM algorithm written from Scratch.

### CODE REVIEW

**Comment by aribis369** [comment]
@Culeshovi Nice work. But one problem is that @imVivekGupta has already worked on SVM and I have merged it. Your's is good, so you have to just change the file name of your ipynb file and  upload it. Another thing before all this, please be very descriptive while writing your Notebooks. These notebook may be read by beginners and should act as a tutorial and not as plain codes. So hoping you make your notebooks more descriptive, then I will merge your PR.

**Comment by aribis369** [comment]
@Culeshovi Can you make your notebooks a little descriptive. Can you work on this, then I will merge your PR.

**Comment by Culeshovi** [comment]
@aribis369 Ok. I'll do the changes.

**Comment by Culeshovi** [comment]
@aribis369  Is this ok?

**Comment by aribis369** [comment]
@Culeshovi Nice work.

**Comment by aribis369** [comment]
Merged.

**Pull request merged**
