### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by anerishah97**

### CODE REVIEW

**Comment by anerishah97** [comment]
I have just changed the Readme file. I don't know why the previous commits are showing up here. 
What should I do?

**Comment by ayanmaity201** [comment]
Good job

**Comment by aribis369** [comment]
@anerishah97 Nice job.

**Comment by aribis369** [comment]
Merged.

**Comment by anerishah97** [comment]
Thank you! @ayanmaity201  @aribis369

**Pull request merged**
