### PR TITLE
Added ML Project Workflow

### PR DESCRIPTION
**Pull request by sanketgautam**
Many Students(Beginners) Face problems regarding how to start a Machine Learning Project, How all the pieces are coupled together to create a fully-functional ML Project.
This PR contains the addition of a Jupyter Notebook which demonstrated basic steps required to build a successful ML project piece-by-piece by taking an example of a simple standard Housing Price Prediction Problem.
It uses following Scientific Libraries - Scikit-Learn, NumPy & Pandas.
It describes and demonstrates the sequence of steps involved in making a ML project from start till the production launch. It also explored multiple options at each step in the process. 
It also provides some tips on best practices to be used, and also provide sufficient exposure of Python's Scientific Libraries to Absolute Beginners.

### CODE REVIEW

**Comment by ayanmaity201** [comment]
Really nice effort.

**Comment by sanketgautam** [comment]
Thanks @ayanmaity201, @aribis369  Can you please merge this PR?

**Comment by aribis369** [comment]
@skg234 Nice tutorial, good explanation.

**Comment by aribis369** [comment]
Merged.

**Pull request merged**
