### PR TITLE
Added PCA

### PR DESCRIPTION
**Pull request by dhruvapte26**
Added Principal component analysis- single value decomposition

### CODE REVIEW

**Comment by aribis369** [comment]
@the-ethan-hunt I have already implemented this part, but your's is also good. Can you please add you notebook to dimension reduction file and create a jupyter notebook for my code also.

**Comment by dhruvapte26** [comment]
Sure, @aribis369 . I will add it in this PR itself

**Comment by dhruvapte26** [comment]
@aribis369 , I have done the shifting. Please merge this Pr. :sweat_smile:

**Comment by aribis369** [comment]
@the-ethan-hunt Can you make jupyter notebook for my code also. I'll merge this PR after that.

**Comment by dhruvapte26** [comment]
@aribis369 , the file has been created by another coder. :sweat_smile:

**Comment by aribis369** [comment]
@the-ethan-hunt PCA was present earlier but it's fine I'm merging your PR. But please see what things are previously done and then start working on something, this we may work on new that that not have been done. As you know we are growing the scope of this project by adding examples of tensorflow and pytorch, which may require more time and more enthusiastic contributors.

**Pull request merged**
