### PR TITLE
Updated with an Example and Definations Of Decision Tree

### PR DESCRIPTION
**Pull request by kparitosh21**
Kindly Check the pr

### CODE REVIEW

**Comment by ayanmaity201** [comment]
Put that notebook in the exmples-scikit folder as it has used the sklearn decision tree classifier. If you build a decision tree from scratch then only make a folder decisiontree.

**Comment by kparitosh21** [comment]
should i create another pr?

**Comment by ayanmaity201** [comment]
You have to delete the DecisionTree folder and make another PR.

**Comment by aribis369** [comment]
@Lightning-Bug I'll merge it.

**Pull request merged**
