### PR TITLE
Pytorch Example implementing Logistic Regression

### PR DESCRIPTION
**Pull request by ayanmaity201**
I have made a notebook in which I have implemented Logistic Regression using Pytorch Tensor instead of using Numpy ndarray. I implemented this ML algorithm on BiomechanicalPatients.csv data . I have uploaded the data and the Pytorch_Tutorial_1.ipynb in the examples-pytorch folder. Please merge my Pull Request.

### CODE REVIEW

**Comment by ayanmaity201** [comment]
In this notebook the Logistic Regression is implemented from scratch. I used pytorch Tensors to familiarize beginners how tensors can be used instead of numpy ndarray. So, I actually did not use ML libraries form pytorch in this notebook.

**Comment by aribis369** [comment]
@ayanmaity201 Good example to get started.

**Comment by aribis369** [comment]
@ayanmaity201 Please try and add more complex algorithms.

**Comment by aribis369** [comment]
Merged.

**Pull request merged**
