### PR TITLE
HandWritten Digit Recognition using MLPClassifier

### PR DESCRIPTION
**Pull request by ayanmaity201**
I have developed a HandWritten Digit Recognition with the help of MLPClassifier from sklearn on MNIST data. I have uploaded the MNIST.ipynb notebook in examples-scikit folder . Please approve the Pull Request.

### CODE REVIEW

**Comment by ayanmaity201** [comment]
I don't know why the PR is showing the previous commits also though they were merged before.

**Comment by aribis369** [comment]
@ayanmaity201 Nice work. Your previous commits are showing, most probably, because you may be using the same branch to sent both the PRs. If PRs sent from same branch the just pile up. Here forth try solving different issues on different branches.

**Comment by aribis369** [comment]
Merged.

**Comment by ayanmaity201** [comment]
Thanks @aribis369

**Pull request merged**
