### PR TITLE
Part 1 of reinforcement learning

### PR DESCRIPTION
**Pull request by devanshb26**
Upper Confidence Bound Learning.The Given Code is used to find which out of the 10 ads to be displayed on website for maximum Click Through Response by the user. 
The dataset is virtual showing what the ith user would have done if one of the 10 ads was shown to him i.e. 1 specifying he would have clicked it and 0 means he would have ignored the add

### CODE REVIEW

**Comment by ayanmaity201** [comment]
@devanshb26 , Make different folder for those commits .They should  be under a folder named like Reinforcement_learning or something of your choice .

**Comment by devanshb26** [comment]
How to merge the files into a folder.I am new to using git and don't know how to  do it.

**Comment by ayanmaity201** [comment]
You don't have to merge it . @aribis369 will do that. You have to take those files a new folder.

**Comment by aribis369** [comment]
@devanshb26 Your work is impressive but can you make jupyter notebooks with nice explanation of the programs, our project aims to act as a tutorial for a beginner to ML so explanations to programs are necessary. 
To upload files to folder you can just use the github website to just drag and drop the files in a folder, if you are not acquainted with git .

**Comment by aribis369** [comment]
@devanshb26 I advice you to close this PR and create a new one. Now while uploading a file create a folder named reenforcement-learning and put your files there and upload it, by just dragging and dropping.

**Pull request closed without merging**
